### ISSUE TITLE
Compatibility issues with Magento 2.2

### ISSUE THREAD

**Issue by xonu** [Magenerds/RichSnippet#1]
We have just changed the version compatibility line in composer.json of the module to:
"magento/framework": "100.0.*|100.1.*|101.0.*",

After installation we cannot load frontend.
Apache log saves the following error:

`[Thu Oct 19 17:07:31.884103 2017] [php7:warn] [pid 14980:tid 1912] [client 127.0.0.1:52432] PHP Warning:  include(): Failed opening '/htdocs/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php' for inclusion (include_path='/htdocs/generated/code;/htdocs/generated/code;/htdocs/vendor/magento/zendframework1/library;/php/PEAR') in /htdocs/vendor/magento/framework/Code/Generator/Io.php on line 160`

**Comment by sydekumf** [comment]
In general this extension is not ready for 2.2 and we haven't tried it out in 2.2. But we are open for pull requests for that :-) I expect, that there is not much or any change necessary in order to be compatible with 2.2.
Your error seems more like an installation problem? Did you try to delete the generated directory again?

**Comment by Mardl** [comment]
Ready for Magento 2.3
